# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
# version: "2"

version: '3'
services:
  minio:
    container_name: minio-server
    image: minio/minio:latest
    ports:
      - 9005:9005
      # - 9000:9000
      - 9002:9001
    volumes:
      - c:\Users\PC\Desktop\Minio_Datalake:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    networks:
      - minio_network



  postgres:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root_db
    networks:
      - minio_network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    networks:
      - minio_network


networks:
  minio_network:
    driver: bridge